server:
  port: 7001
server.error.include-message: always
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
logging:
  level:
    root: INFO
    com.shine2share.product: DEBUG
---
spring.config.activate.on-profile: docker
server:
  port: 9000
spring.data.mongodb:
  host: mongodb
  port: 27017