server:
  port: 7002
  error:
    include-message: always
spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db
logging:
  level:
    root: INFO
    com.shine2share.recommendation: DEBUG
---
spring.config.activate.on-profile: docker
server:
  port: 9001
spring.data.mongodb.host: mongodb